### ISSUE TITLE
tracking retweets and favs

### ISSUE THREAD

**Issue by stephanlindauer** [SpiderStrategies/node-tweet-stream#28]
hi there,
first of all: thanks for this lib! ;-)
i was wondering is there a way to get updates when a tweet is retweeted or fav'ed? 
cheers
stephan

**Comment by nathanbowser** [comment]
Sure, we'll take a PR

**Comment by nathanbowser** [comment]
@stephanlindauer I think the retweet data is available on an incoming tweet message. You can use that to figure out if the tweet was original or retweeted.
