### ISSUE TITLE
language missing in hasFilters

### ISSUE THREAD

**Issue by alegrm** [SpiderStrategies/node-tweet-stream#30]
Isn't language.length missing in this line?

https://github.com/SpiderStrategies/node-tweet-stream/blob/master/lib/twitter.js#L181

**Comment by nathanbowser** [comment]
Looks like it. PR welcome

**Comment by jeveloper** [comment]
Looks like its fixed in 1.9

**Comment by nathanbowser** [comment]
Yep, fixed in https://github.com/SpiderStrategies/node-tweet-stream/pull/26/files

Thanks for reminding me, @jeveloper
