### ISSUE TITLE
Can't track users

### ISSUE THREAD

**Issue by Moezalez** [SpiderStrategies/node-tweet-stream#37]
Tracking user like this: `twitter.follow('moezalez');` doesn't work for me. 
It just doesn't track anything without any error notification. 
Twitter returns `406`
https://dev.twitter.com/streaming/overview/connecting

**Comment by nathanbowser** [comment]
I don't currently use the `follow` feature, so wasn't aware of this. Perhaps twitter changed the API since this features was coded?

PR definitely welcome.

**Comment by Moezalez** [comment]
@nathanbowser 
Hey Nathan, I just realised I made a mistake. it is still working, though you need the User ID instead of the handle.
