### ISSUE TITLE
Is there a way to simply Untrack all

### ISSUE THREAD

**Issue by LoganArnett** [SpiderStrategies/node-tweet-stream#45]
Trying to figure out the way to untrack all for an application that allows the users to track and untrack in bulk requests.

Something like `untrack.all();` or is there a disconnect function or something like that?

Thanks

**Comment by nathanbowser** [comment]
Yea, https://github.com/SpiderStrategies/node-tweet-stream/blob/9bfd4e2ea1819a5d55ede822cbd5cb133888497c/lib/twitter.js#L183 but I think it's only for tracking keywords, not locations and other events.

**Comment by LoganArnett** [comment]
Awesome thanks @nathanbowser for the quick response! 👍
